spring:
  application:
    name: teqnolo_api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/teqnolo}
    username: ${SPRING_DATASOURCE_USERNAME:teqnolo}
    password: ${SPRING_DATASOURCE_PASSWORD:teqnolo}
